# This is a basic workflow to help you get started with Actions

name: Deploy to Prod

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        
      - name: Install npm dependencies
        run: npm install
      - name: Run build task
        run: npm run build

      - name: Deploy to Server via sshdeploy
        uses: easingthemes/ssh-deploy@v2.1.4
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PROD_SSH_KEY }}
          ARGS: "-rlzv --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.PROD_REMOTE_HOST }}
          REMOTE_PORT: ${{ secrets.PROD_SSH_PORT }}
          REMOTE_USER: ${{ secrets.PROD_REMOTE_USER }}
          TARGET: ${{ secrets.PROD_REMOTE_TARGET }}
